config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :with_reviews ,only: [:index]
    collection do
      get 'search'
    end
  end
  resources :casts do
    collection do
      get 'search'
    end
  end
  resources :products do
    resources :product_likes, only: [:create, :destroy]
    resources :product_structures, only: [:new, :create]
    resources :reviews, only: [:new, :create] do
      resources :review_likes, only: [:create, :destroy]
      resources :review_comments, only: [:new, :create]
    end
    collection do
      get 'search'
    end
  end
  root 'products#index'
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  has_many :products_casts
  has_many :products, through: :products_casts
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_url, ImageUrlUploader
  belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_likes, dependent: :destroy
  has_many :product_structures
  has_many :products_casts
  has_many :casts, through: :products_casts
  has_many :reviews
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  def product_like_user(user_id)
    product_likes.find_by(user_id: user_id)
  end

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/product_like.rb
class ProductLike < ActiveRecord::Base
  belongs_to :product, counter_cache: :likes_count
  belongs_to :users
end

app/models/product_structure.rb
class ProductStructure < ActiveRecord::Base
  belongs_to :product
end

app/models/products_cast.rb
class ProductsCast < ActiveRecord::Base
  belongs_to :product
  belongs_to :cast
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  has_many :review_likes, dependent: :destroy
  has_many :review_comments

  validates :rate, presence: true
  validates :title, presence: true
  validates :review, presence: true

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/review_comment.rb
class ReviewComment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/models/review_like.rb
class ReviewLike < ActiveRecord::Base
  belongs_to :review, counter_cache: :likes_count
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :product_likes
  has_many :review_likes
  has_many :reviews
  has_many :review_comments
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  validates :nickname, presence: true

  enum status: {draft: 0, published: 1}

end

app/controllers/casts_controller.rb
class CastsController < ApplicationController

  def show
    @cast = Cast.find(params[:id])
  end

  def search
    @casts = Cast.where('cast LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: :new
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    product = Product.find(params[:product_id])
    Review.create(create_params)
    redirect_to controller: :products, action: :show, id: product.id
  end

  private
  def create_params
    params.require(:review).permit(:rate, :title, :review).merge(product_id: params[:product_id], user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    product_ids = @user.reviews.group(:product_id).order('count_product_id DESC').count(:product_id).keys
    @reviews = product_ids.map { |id| Product.find(id) }
  end

  def edit
    current_user.build_image if current_user.image.blank?
  end

  def create
    current_user.create(user_params)
  end

  def search
    @users = User.where('nickname LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  def update
    current_user.update(user_params)
    redirect_to controller: :users, action: :show
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :gender, :introduction, :image_cache, image_attributes: [:id, :image_url])
  end

end

app/controllers/with_reviews_controller.rb
class WithReviewsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @reviews = @user.reviews.includes(:product)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/product_likes_helper.rb
module ProductLikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_likes_helper.rb
module ReviewLikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/with_reviews_helper.rb
module WithReviewsHelper
end

app/views/with_reviews/_reviewitem.html.erb
<div class="row reviewitem">
  <div class="col-xs-5">
    <%= link_to product_path(product) do %>
      <div class="reviewitem-image">
        <%= image_tag product.image.image_url %>
      </div>
    <% end %>
  </div>
  <div class="col-xs-7">
    <p class="reviewitem-product-title"><%= product.title %></p>
    <p class="reviewitem-rate"><i class="fa fa-star fa-fw" aria-hidden="true"></i><span class="rate-number"><%= review.rate %></span></p>
    <p class="reviewitem-title"><%= review.title %></p>
    <p class="reviewitem-text"><%= review.review %></p>
    <p class="reviewitem-date text-right"><%= review.created_at.strftime('%Y年%m月%d日') %></p>
  </div>
</div>

app/views/with_reviews/index.html.erb
<div class="container-fluid">
  <div class="row user-page">
    <div class="col-md-10 col-md-offset-1">
      <div class="row user-profile">
        <div class="col-md-2 col-sm-3 col-xs-5 user-image">
          <% if @user.image.present? %>
            <%= image_tag @user.image.image_url.thumb, class:"img-thumbnail" %>
          <% else %>
            <%= image_tag "default.png", class:"profile-image img-thumbnail" %>
          <% end %>
        </div>
        <div class="col-md-10 col-sm-9 col-xs-7">
          <h1 class="user-nickname"><%= @user.nickname %></h1>
          <% if @user == current_user %>
            <%= link_to edit_user_path(current_user), class:"btn btn-default btn-xs" do %>
              <i class="fa fa-cog fa-fw" aria-hidden="true"></i>プロフィール編集
            <% end %>
          <% end %>
          <p class="user-introduction"><%= @user.introduction %></p>
        </div>
      </div>
      <div class="row">
       <div role="tabpanel">
        <ul class="nav nav-tabs nav-justified nav-head" role="tablist">
          <li role="presentation" class="active"><a href="#review" data-toggle="tab">レビュー(<%= @reviews.count %>作品)</a></li>
          <li role="presentation" ><a href="#product" data-toggle="tab">ブックマーク(<%= @user.product_likes.count %>作品)</a></li>
        </ul>
        <div id="userTabContent" class="container-fluid tab-content">
          <div class="tab-content row">
            <div role="tabpanel" class="tab-pane active" id="review">
              <ul class="list-inline text-right review-change black-link">
                <li>
                  <%= link_to user_path(@user) do %>
                    <i class="fa fa-th-large fa-2x" aria-hidden="true"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to user_with_reviews_path(@user) do %>
                    <i class="fa fa-th-list fa-2x" aria-hidden="true"></i>
                  <% end %>
                </li>
              </ul>
              <% @reviews.each do |review| %>
                <div class="col-sm-6 ">
                  <%= render partial: "with_reviews/reviewitem", locals: {product: review.product, review: review} %>
                </div>
              <% end %>
            </div>
            <div role="tabpanel" class="tab-pane" id="product">
              <% @user.product_likes.each do |product_like| %>
                <div class="col-md-3 col-sm-4 col-xs-6">
                  <%= render partial: "common/productitem", locals: {product: product_like.product, review_rate: product_like.product.reviews.average(:rate).round(1)} %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
       </div>
      </div>
    </div>
  </div>
</div>