config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :with_reviews ,only: [:index]
    collection do
      get 'search'
    end
  end
  resources :casts do
    collection do
      get 'search'
    end
  end
  resources :products do
    resources :product_likes, only: [:create, :destroy]
    resources :product_structures, only: [:new, :create]
    resources :reviews, only: [:new, :create] do
      resources :review_likes, only: [:create, :destroy]
      resources :review_comments, only: [:new, :create]
    end
    collection do
      get 'search'
    end
  end
  root 'products#index'
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  has_many :products_casts
  has_many :products, through: :products_casts
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_url, ImageUrlUploader
  belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_likes, dependent: :destroy
  has_many :product_structures
  has_many :products_casts
  has_many :casts, through: :products_casts
  has_many :reviews
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  def product_like_user(user_id)
    product_likes.find_by(user_id: user_id)
  end

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/product_like.rb
class ProductLike < ActiveRecord::Base
  belongs_to :product, counter_cache: :likes_count
  belongs_to :users
end

app/models/product_structure.rb
class ProductStructure < ActiveRecord::Base
  belongs_to :product
end

app/models/products_cast.rb
class ProductsCast < ActiveRecord::Base
  belongs_to :product
  belongs_to :cast
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  has_many :review_likes, dependent: :destroy
  has_many :review_comments

  validates :rate, presence: true
  validates :title, presence: true
  validates :review, presence: true

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/review_comment.rb
class ReviewComment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/models/review_like.rb
class ReviewLike < ActiveRecord::Base
  belongs_to :review, counter_cache: :likes_count
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :product_likes
  has_many :review_likes
  has_many :reviews
  has_many :review_comments
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  validates :nickname, presence: true

  enum status: {draft: 0, published: 1}

end

app/controllers/casts_controller.rb
class CastsController < ApplicationController

  def show
    @cast = Cast.find(params[:id])
  end

  def search
    @casts = Cast.where('cast LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    product_ids = @user.reviews.group(:product_id).order('count_product_id DESC').count(:product_id).keys
    @reviews = product_ids.map { |id| Product.find(id) }
  end

  def edit
    current_user.build_image if current_user.image.blank?
  end

  def create
    current_user.create(user_params)
  end

  def search
    @users = User.where('nickname LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  def update
    current_user.update(user_params)
    redirect_to controller: :users, action: :show
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :gender, :introduction, :image_cache, image_attributes: [:id, :image_url])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/product_likes_helper.rb
module ProductLikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_likes_helper.rb
module ReviewLikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/with_reviews_helper.rb
module WithReviewsHelper
end

app/views/common/_footer.html.erb
<div class="container-fluid footer">
  <div class="text-center">
    ©Dlama Inc. All Rights Reserved.
  </div>
</div>

app/views/common/_header.html.erb
<nav class="header navbar navbar-default">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand header-logo hidden-lg hidden-md" href="/">
            <%= image_tag 'logo.png' %>
          </a>
          <a class="navbar-brand header-logo hidden-sm hidden-xs" href="/">
            <%= image_tag 'logo2.png' %>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <form class="navbar-form navbar-left hidden-xs" role="search">
            <% if current_page?('/products/search') %>
              <%= form_tag('/products/search', method: :get) do %>
                <div class="form-group">
                  <input type="text" name="keyword" class="form-control" placeholder="作品名で検索" size="30">
                </div>
                <button type="submit" class="btn btn-primary">検索</button></input>
              <% end %>
            <% end %>
            <% if current_page?('/casts/search') %>
              <%= form_tag('/casts/search', method: :get) do %>
                <div class="form-group">
                  <input type="text" name="keyword" class="form-control" placeholder="キャストで検索" size="30">
                </div>
                <button type="submit" class="btn btn-primary">検索</button></input>
              <% end %>
            <% end %>
            <% if current_page?('/users/search') %>
              <%= form_tag('/users/search', method: :get) do %>
                <div class="form-group">
                  <input type="text" name="keyword" class="form-control" placeholder="ユーザー名で検索" size="30">
                </div>
                <button type="submit" class="btn btn-primary">検索</button></input>
              <% end %>
            <% end %>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && current_user.published? %>
              <li>
                <%= link_to new_product_path do %>
                  <span class="product-post-btn">作品投稿</span>
                <% end %>
              </li>
            <% end %>
            <li class="dropdown hidden-xs">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="search">検索</span><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "ドラマ検索", search_products_path %>
                </li>
                <li class="entry-button">
                  <%= link_to 'キャスト検索', search_casts_path %>
                </li>
                <li>
                  <%= link_to "ユーザー検索", search_users_path %>
                </li>
              </ul>
            </li>
          <% if user_signed_in? %>
            <li class="hidden-xs">
              <li class="hidden-xs">
                <% if current_user.image.present? %>
                  <%= image_tag current_user.image.image_url, class:"header-user-image img-circle" %>
                <% else %>
                  <%= image_tag "default.png", class:"header-user-image img-circle" %>
                <% end %>
              </li>
              <li class="dropdown hidden-xs">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="username"><%= current_user.nickname %></span><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to "マイページ", user_path(current_user) %>
                  </li>
                  <li>
                    <%= link_to "プロフィール編集", edit_user_path(current_user) %>
                  </li>
                  <li class="entry-button">
                    <%= link_to 'サインアウト', destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            </li>
            <li>
              <ul class="list-inline visible-xs-block">
                <li>
                  <%= link_to user_path(current_user) do %>
                    <% if current_user.image.present? %>
                      <%= image_tag current_user.image.image_url, class:"header-user-image img-circle" %>
                    <% else %>
                      <%= image_tag "default.png", class:"header-user-image img-circle" %>
                    <% end %>
                  <% end %>
                </li>
                <li class="black-link">
                  <%= link_to current_user.nickname, user_path(current_user) %>
                </li>
              </ul>
              <li class="visible-xs-block">
                <%= link_to "プロフィール編集", edit_user_path(current_user) %>
              </li>
              <li class="visible-xs-block">
                <%= link_to 'サインアウト', destroy_user_session_path, method: :delete %>
              </li>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_registration_path, class: 'post' do %>
                <span class="top-registration">アカウント作成</span>
              <% end %>
            </li>
            <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
          <% end %>
        </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_productitem.html.erb
<div class="product-item black-link">
  <%= link_to product_path(product) do %>
    <div class="image">
      <%= image_tag product.image.image_url %>
    </div>
  <% end %>
  <div class="line">
    <%= link_to product_path(product) do %>
      <div class="title text-center">
        <%= product.title %>
      </div>
    <% end %>
    <div class="review text-center">
      <i class="fa fa-star fa-fw" aria-hidden="true"></i>
      <span class="rate-number"><%= review_rate %></span>
    </div>
  </div>
</div>
<ul class="data list-inline text-center">
  <li class="marks text-center">
    <%= link_to new_product_review_path(product) do %>
      <i class="fa fa-pencil fa-fw" aria-hidden="true"></i><%= product.reviews.count.to_i %>
    <% end %>
  </li>
  <li class="clip text-center">
    <i class="fa fa-bookmark fa-fw" aria-hidden="true"></i><%= product.likes_count.to_i %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset = 'utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>DLama</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render partial: "common/header" %>

  <%= yield %>

  <%= render partial: "common/footer" %>

  </body>
</html>