config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :with_reviews ,only: [:index]
    collection do
      get 'search'
    end
  end
  resources :casts do
    collection do
      get 'search'
    end
  end
  resources :products do
    resources :product_likes, only: [:create, :destroy]
    resources :product_structures, only: [:new, :create]
    resources :reviews, only: [:new, :create] do
      resources :review_likes, only: [:create, :destroy]
      resources :review_comments, only: [:new, :create]
    end
    collection do
      get 'search'
    end
  end
  root 'products#index'
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  has_many :products_casts
  has_many :products, through: :products_casts
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_url, ImageUrlUploader
  belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_likes, dependent: :destroy
  has_many :product_structures
  has_many :products_casts
  has_many :casts, through: :products_casts
  has_many :reviews
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  def product_like_user(user_id)
    product_likes.find_by(user_id: user_id)
  end

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/product_like.rb
class ProductLike < ActiveRecord::Base
  belongs_to :product, counter_cache: :likes_count
  belongs_to :users
end

app/models/product_structure.rb
class ProductStructure < ActiveRecord::Base
  belongs_to :product
end

app/models/products_cast.rb
class ProductsCast < ActiveRecord::Base
  belongs_to :product
  belongs_to :cast
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  has_many :review_likes, dependent: :destroy
  has_many :review_comments

  validates :rate, presence: true
  validates :title, presence: true
  validates :review, presence: true

  def review_like_user(user_id)
    review_likes.find_by(user_id: user_id)
  end

end

app/models/review_comment.rb
class ReviewComment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/models/review_like.rb
class ReviewLike < ActiveRecord::Base
  belongs_to :review, counter_cache: :likes_count
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :product_likes
  has_many :review_likes
  has_many :reviews
  has_many :review_comments
  has_one :image, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :image

  validates :nickname, presence: true

  enum status: {draft: 0, published: 1}

end

app/controllers/casts_controller.rb
class CastsController < ApplicationController

  def show
    @cast = Cast.find(params[:id])
  end

  def search
    @casts = Cast.where('cast LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where(date_day: Date.today.wday).limit(6)
    @nextproducts = Product.where(date_day: Date.today.next.wday).limit(6)
    product_ids = Review.group(:product_id).order('count_product_id DESC').limit(3).count(:product_id).keys
    @ranking = product_ids.map { |id| Product.find(id) }
  end
  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.order("created_at DESC").page(params[:page]).per(10)
    if user_signed_in?
      @like = ProductLike.find_by(user_id: current_user.id, product_id: params[:id])
      @review_like = ReviewLike.find_by(user_id: current_user.id)
    end
    @recommendedproducts = Product.where(company: @product.company).limit(3)
  end

  def search
    @products = Product.where('title LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  def new
    @product = Product.new
    @product.build_image
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to controller: :products, action: :show, id: @product.id
  end


  def edit
    @product = Product.find(params[:id])
    @product.build_image if @product.image.blank?
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to controller: :products, action: :show, id: @product.id
  end

  private
  def product_params
    params.require(:product).permit(:title, :detail, :date, :twitter, :wikipedia, :amazon, :site, :image_url, :company, :director, :playwrite, :site, :date_day, image_attributes: [:id, :image_url])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: :new
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    product = Product.find(params[:product_id])
    Review.create(create_params)
    redirect_to controller: :products, action: :show, id: product.id
  end

  private
  def create_params
    params.require(:review).permit(:rate, :title, :review).merge(product_id: params[:product_id], user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    product_ids = @user.reviews.group(:product_id).order('count_product_id DESC').count(:product_id).keys
    @reviews = product_ids.map { |id| Product.find(id) }
  end

  def edit
    current_user.build_image if current_user.image.blank?
  end

  def create
    current_user.create(user_params)
  end

  def search
    @users = User.where('nickname LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  def update
    current_user.update(user_params)
    redirect_to controller: :users, action: :show
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :gender, :introduction, :image_cache, image_attributes: [:id, :image_url])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/product_likes_helper.rb
module ProductLikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_comments_helper.rb
module ReviewCommentsHelper
end

app/helpers/review_likes_helper.rb
module ReviewLikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/with_reviews_helper.rb
module WithReviewsHelper
end

app/views/casts/search.html.erb
<div class="container-fluid">
  <div class="row cast-search">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <% @casts.each do |cast| %>
          <div class="col-md-2 col-sm-3 col-xs-6">
            <%= link_to cast_path(cast) do %>
              <div class="image">
                <img src="" alt=""/>
              </div>
              <div class="cast text-center">
                <p><%= cast.cast %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/casts/show.html.erb
<div class="container-fluid">
  <div class="row cast-product-detail">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <h4 class="cast-drama text-center"><%= @cast.cast %>の出演ドラマ <%= @cast.products_casts.count %>作品</h4>
          <% @cast.products.each do |product| %>
            <div class="col-md-3 col-sm-4 col-xs-6">
              <%= link_to product_path(product) do %>
                <div class="image">
                  <%= image_tag product.image.image_url %>
                </div>
                <div class="title text-center">
                  <p><%= product.title %></p>
                </div>
              <% end %>
              <ul class="data list-inline text-center">
                <li class="marks text-center"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span><%= product.likes_count %></li>
                <li class="clip text-center">
                  <%= link_to new_product_review_path(product) do %>
                    <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span><%= product.reviews.count %>
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container-fluid">
  <div class="row product-edit">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="text-center">
          <h3>作品編集</h3>
          <hr>
        </div>

        <div class="personal_data col-sm-8 col-sm-offset-2">
          <div class="row form-horizontal">
            <%= form_for @product do |f| %>
              <div class="form-group">
                <%= f.label :タイトル, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :title, placeholder: "題名", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :画像, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.fields_for :image do |image| %>
                    <%= image.file_field :image_url %>
                  <% end %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :曜日, class: "control-label col-sm-3" %>
                  <div class="col-sm-3">
                    <%= f.number_field :date, placeholder: "曜日", class: "form-control" %>
                  </div>
              </div>

              <div class="form-group">
                <%= f.label :会社, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :company, placeholder: "制作", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :あらすじ, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_area :detail, placeholder: "あらすじ", class: "form-control", rows: "5" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :公式サイト, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :site, placeholder: "サイト", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :twitter, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :twitter, placeholder: "twitter", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :Wikipedia, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :wikipedia, placeholder: "wikipedia", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :amazon, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :amazon, placeholder: "amazon", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :演出, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :director, placeholder: "演出", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :脚本家, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :playwrite, placeholder: "脚本", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :放送日, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.date_select :date, {discard_day: true, default: Time.now, start_year: 2000}, {class: "form-control form-product-date"} %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-9 col-sm-offset-3">
                  <%= f.submit "変更内容を保存する", class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row product-show">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="lineup col-md-9">
          <div class="row">
            <div class="top-content-header">
              今日のラインナップ
            </div>
            <% @products.each do |product| %>
              <div class="col-md-4 col-sm-4 col-xs-6">
                <%= render partial: "common/productitem", locals: {product: product, review_rate: product.reviews.average(:rate).round(1)} %>
              </div>
            <% end %>
          </div>
          <div class="row">
            <div class="top-content-header">
              明日のラインナップ
            </div>
            <% @nextproducts.each do |product| %>
              <div class="col-md-4 col-sm-4 col-xs-6">
                <%= render partial: "common/productitem", locals: {product: product, review_rate: product.reviews.average(:rate).round(1)} %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="top-ranking col-md-3">
          <div class="row panel panel-default top-ranking-panel">
            <div class="top-content-header panel-heading">
              <i class="fa fa-users fa-fw" aria-hidden="true"></i>みんなのランキング
            </div>
            <% @ranking.each.with_index(1) do |product, i| %>
              <div class="col-md-12 col-sm-4 col-xs-6 panel-body">
                <%= render partial: "common/productitem", locals: {product: product, review_rate: product.reviews.average(:rate).round(1)} %>
                <p class="ranking-text ranking-text-<%= i %>">
                  <span><%= i %></span>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container-fluid">
  <div class="row product-registration">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="text-center">
          <h3>作品登録</h3>
        </div>

        <hr>

        <div class="product_data col-sm-8 col-sm-offset-2">
          <div class="row form-horizontal">
            <%= form_for @product do |f| %>
              <div class="form-group">
                <%= f.label :タイトル, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :title, placeholder: "題名", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :画像, class: "control-label col-sm-3" %>
                  <div class="col-sm-9">
                    <%= f.fields_for :image do |image| %>
                      <%= image.file_field :image_url %>
                    <% end %>
                  </div>
              </div>

              <div class="form-group">
                <%= f.label :曜日, class: "control-label col-sm-3" %>
                  <div class="col-sm-3">
                    <%= f.number_field :date, placeholder: "曜日", class: "form-control" %>
                  </div>
              </div>

              <div class="form-group">
                <%= f.label :会社, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :company, placeholder: "制作", class: "form-control" %>
                </div>
              </div>


              <div class="form-group">
                <%= f.label :あらすじ, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_area :detail, placeholder: "あらすじ", class: "form-control", rows: "5" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :公式サイト, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :site, placeholder: "サイト", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :twitter, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :twitter, placeholder: "twitter", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :Wikipedia, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :wikipedia, placeholder: "wikipedia", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :amazon, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :amazon, placeholder: "amazon", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :演出, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :director, placeholder: "演出", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :脚本家, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :playwrite, placeholder: "脚本", class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :放送日, class: "control-label col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.date_select :date, {discard_day: true, default: Time.now, start_year: 2000}, {class: "form-control form-product-date"} %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-9 col-sm-offset-3">
                  <%= f.submit "内容を保存する", class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<div class="container-fluid">
  <div class="row product-search">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-md-3 col-sm-4 col-xs-6">
            <%= render partial: "common/productitem", locals: {product: product, review_rate: product.reviews.average(:rate).round(1)} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row edit-user">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="site_detail text-center">
          <h3>プロフィール編集</h3><hr>
        </div>
            <div class="personal_data col-sm-8 col-sm-offset-2">
              <div class="row form-horizontal">
                <%= form_for current_user do |f| %>

                    <div class="form-group">
                      <%= f.label :ニックネーム, class: "control-label col-sm-3" %>
                      <div class="col-sm-9">
                        <%= f.text_field :nickname, placeholder: "ニックネーム(必須)", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :プロフィール画像, class: "control-label col-sm-3" %>
                        <div class="col-sm-9">
                          <%= f.fields_for :image do |image| %>
                            <%= image.file_field :image_url %>
                          <% end %>
                        </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :メールアドレス, class: "control-label col-sm-3" %>
                      <div class="col-sm-9">
                        <%= f.email_field :email, placeholder: "メールアドレス", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :性別, class: "sr-only" %>
                      <div class="col-sm-9 col-sm-offset-3">
                        <label><%= f.radio_button :gender, "1" %>男性</label>
                        <label><%= f.radio_button :gender, "2" %>女性</label>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :自己紹介, class: "control-label col-sm-3" %>
                      <div class="col-sm-9">
                        <%= f.text_area :introduction, placeholder: "自己紹介", class: "form-control", rows: "3" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-sm-9 col-sm-offset-3">
                        <%= f.submit "変更内容を保存する", class: "btn btn-danger" %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="container-fluid">
  <div class="row user-search">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-2 col-sm-3 col-xs-4 user-image text-center">
            <%= link_to user_path(user) do %>
              <% if user.image.present? %>
                <%= image_tag user.image.image_url, class:"profile-images img-responsive center-block img-rounded" %>
              <% else %>
                <%= image_tag "default.png", class:"profile-images img-responsive center-block" %>
              <% end %>        　
                <p><%= user.nickname %></p>
            <% end %>
            <ul class="list-inline">
              <li class="fa fa-pencil fa-fw" aria-hidden="true"></li><%= user.reviews.count %>
              <li class="fa fa-bookmark fa-fw" aria-hidden="true"></li><%= user.product_likes.count %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row user-page">
    <div class="col-md-10 col-md-offset-1">
      <div class="row user-profile">
        <div class="col-md-2 col-sm-3 col-xs-5 user-image">
          <% if @user.image.present? %>
            <%= image_tag @user.image.image_url.thumb, class:"img-thumbnail" %>
          <% else %>
            <%= image_tag "default.png", class:"profile-image img-thumbnail" %>
          <% end %>
        </div>
        <div class="col-md-10 col-sm-9 col-xs-7">
          <h1 class="user-nickname"><%= @user.nickname %></h1>
          <% if @user == current_user %>
            <%= link_to edit_user_path(current_user), class:"btn btn-default btn-xs" do %>
              <i class="fa fa-cog fa-fw" aria-hidden="true"></i>プロフィール編集
            <% end %>
          <% end %>
          <p class="user-introduction"><%= @user.introduction %></p>
        </div>
      </div>
      <div class="row">
       <div role="tabpanel">
        <ul class="nav nav-tabs nav-justified nav-head" role="tablist">
          <li role="presentation" class="active"><a href="#review" data-toggle="tab">レビュー(<%= @reviews.count %>作品)</a></li>
          <li role="presentation" ><a href="#product" data-toggle="tab">ブックマーク(<%= @user.product_likes.count %>作品)</a></li>
        </ul>
        <div id="userTabContent" class="container-fluid tab-content">
          <div class="tab-content row">
            <div role="tabpanel" class="tab-pane active" id="review">
             <% @reviews.each.with_index do |product| %>
              <div class="col-md-3 col-sm-4 col-xs-6">
                <%= render partial: "common/productitem", locals: {product: product, review_rate: product.reviews.average(:rate).round(1)} %>
              </div>
             <% end %>
            </div>
            <div role="tabpanel" class="tab-pane" id="product">
              <% @user.product_likes.each do |product_like| %>
              <div class="col-md-3 col-sm-4 col-xs-6">
                <%= render partial: "common/productitem", locals: {product: product_like.product, review_rate: product_like.product.reviews.average(:rate).round(1)} %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
       </div>
      </div>
    </div>
  </div>
</div>